const PostsActionsTypes = {
    FETCH_POSTS_START: "FETCH_POSTS_START",
    FETCH_POSTS_SUCCESS: "FETCH_POSTS_SUCCESS",
    FETCH_POSTS_FAILURE: "FETCH_POSTS_FAILURE",
    UPDATE_POSTS: "UPDATE_POSTS",
    DELETE_POST: "DELETE_POST",
    EDIT_POST: "EDIT_POST"
};

export default PostsActionsTypes;