const MonstersActionsTypes = {
    FETCH_MONSTERS_START: "FETCH_MONSTERS_START",
    FETCH_MONSTERS_SUCCESS: "FETCH_MONSTERS_SUCCESS",
    FETCH_MONSTERS_FAILURE: "FETCH_MONSTERS_FAILURE",
    SET_SEARCH_KEY: "SET_SEARCH_KEY"
};

export default MonstersActionsTypes;